from .topology import BaseTopology
from .vertex_attributes import BaseVertexAttributes, PeriodicAttributes
from ..utils.decorators import sampy_class
import xml.etree.ElementTree as ET


@sampy_class
class GraphFromORMxml(BaseTopology,
                      BaseVertexAttributes,
                      PeriodicAttributes):
    """
    Class developed for the need of the Leighton Lab. The graph structure is read from an XML, as generated by Badr
    QGIS module.
    """
    def __init__(self, path_to_xml=None):
        if path_to_xml is None:
            raise ValueError("A path to an ORM XML should be provided.")

